debug: false # 디버그 로그를 활성할건지(로그가 너무 많아서 일단 false로 둠)
management.endpoints.web.exposure.include: "*" # 개발 단계에서 보고싶은 기능을 모두 볼 수 있는

logging:
  level:
    com.fastcampus.projectboard: debug # 패키지에서 발생하는 모든 로그들은 디버그 레벨로 보겠다
    org.springframework.web.servlet: debug # debug로 다 보지 않고, 이렇게 request와 response 로그만 오픈한거
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA 기술 사용할 때 ?같은 Query 로그 관찰할 수 있는

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: board
    password: board
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  defer-datasource-initialization: true
  hibernate.ddl-auto: create # Entity 만 보고 테이블 데이터를 유추해서 자동으로 ddl문을 만들어줌
  show-sql: true
  properties:
    hibernate.format_sql: true
    hibernate.default_batch_fetch_size: 100 # N+1 문제 해결하는 방법
h2.console.enabled: false
sql.init.mode: always # data.sql 언제 작동 시킬 것인지(embedded는 테스트 환경에서만 작동시킨다)

---

spring:
config.activate.on-profile: testdb
#datasource:
#  url: jdbc:h2:mem:board;mode=mysql
#  driver-class-name: org.h2.Driver
#sql.init.mode: always
#test.database.replace: none

server:
  servlet:
    encoding:
      force-response: true